### PR TITLE
add summary template

### PR DESCRIPTION
**Pull request by anastasia-escher**
solves #105
Added a variant curation entries summary template and a link to generate a pdf. 
@dameyerdave please check if the content is ok (styles can be changed later).

### CODE REVIEW

**Comment by dameyerdave** [comment]
Thank s Nastia. I have the following comments:
- It looks very good as a first shot. 
- Can we adapt the color scheme from the website: i.e. set the title to the same color as the main banner: rgb(45,62,79)
- What I miss in the summary are (as separate paragraphs per curation entry):
  - Gene summary
  - Variant Summary
  - Textual evidences
  - Complementary information
  - Personal Comment
- Can we center the content of the report. I mean for the individual listings left alignment is perfect but the view in the browser should somehow be centered and the width should be the same as on a PDF so that it looks like a on the PDF 
Screenshot 2022-05-24 at 09 48 19.
- For the PDF we could add some header with the SVIP logo and the variant name and footer with the page number and date of creation.
- I like the feature of only showing my own curation entries but I'd display it as a checkbox. 
- Can you please move the action buttons (and the checkbox for `show only my entries` to the top of the page like a toolbar)
- Download as PDF should open the PDF in a separate tab.

Many thanks for the adaptations.

**Comment by dameyerdave** [comment]
Can we change the `Show variant curations summary` link to a button with the Text `SVIP Information Summary`
Screenshot 2022-05-24 at 10 09 18

**Comment by anastasia-escher** [comment]
Hi @dameyerdave! Thanks for the comments, I will address  them later. The personal comment should already appear in the current version if there is one and only if the curator is the current user (so, the user can only see his/her personal comment and not the others), doesn't it work? Or should all personal comments be seen by everybody?

**Comment by dameyerdave** [comment]
I added a comment but I cannot see it in the Summary. Also I see the complementary information as `Summary`. I think it makes more sense to put the running text in seperate paragraphs with additional sub headers:
Screenshot 2022-05-24 at 10 29 05

Screenshot 2022-05-24 at 10 29 21

**Comment by dameyerdave** [comment]
Please also be aware to create the Summary template multilingual as described here: [https://docs.djangoproject.com/en/4.0/topics/i18n/translation/](https://docs.djangoproject.com/en/4.0/topics/i18n/translation/)

**Comment by anastasia-escher** [comment]
Ok, alle sklar!
By the way, I have tried to put custom static files to the static folder (with some css and js), but the template didn't see them, so that  the css had to be put into the template and there is no way to use js as inline scripts inside templates are forbidden due to security setting.  It seems that the custom static files are not collected by django when running in a container... Or is it something else? Could you please take a look?

**Comment by dameyerdave** [comment]
I would put the css directly into the report (summary) template, because this belongs to the template itself and should not have something to do with the UI itself. Regarding js in templates, yes this is prohibited and should not be used. JS cannot run inside PDF, therefor I do not understand why It should be necessary to use js inside a template? :thinking:

**Pull request merged**
